[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.12.15", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "debug-print",
    "mock",
    "macros",
    "with-chrono",
    "with-json",
    "with-uuid",
] }
