services:
  # archery-db-service:
  #   build: archery-tools-server
  #   ports:
  #     - 8080:8080
  db:
    image: postgres
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_USER: postgres # Just use the default value but keep this line for clarity
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: archery-db

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 7080:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
